import React,{useState,useId} from 'react';
import {useApp} from '../../context/AppContext';
import {AreaChart,Area,CartesianGrid,XAxis,YAxis,Tooltip,ResponsiveContainer,ReferenceLine} from 'recharts';
import {accuracy,comparisonKey,summarize} from '../../lib/statistics';
export const ShooterProgress:React.FC<{compact?:boolean}>=({compact=false})=>{
 const {getMyResults,getMyFocusItems,updateFocusItemStatus}=useApp();const results=getMyResults();const [choice,setChoice]=useState(''),[metric,setMetric]=useState<'hf'|'accuracy'|'time'>('hf'),[period,setPeriod]=useState('all');const gradientId=useId().replace(/:/g,'');
 const groups=new Map<string,typeof results>();for(const r of results){const key=comparisonKey(r);if(key)groups.set(key,[...(groups.get(key)||[]),r]);}
 const selected=groups.has(choice)?choice:[...groups.keys()][0]||'',all=groups.get(selected)||[];
 const cutoff=period==='all'?'':new Date(Date.now()-Number(period)*86400000).toISOString().slice(0,10);const filtered=all.filter(r=>!cutoff||r.trainingDate>=cutoff);const stats=summarize(filtered),mode=all[0]?.measurementType;const effectiveMetric=mode==='points'&&metric==='hf'?'accuracy':metric;
 const chart=stats.data.map(r=>({date:r.trainingDate,value:effectiveMetric==='hf'?r.hitFactor:effectiveMetric==='time'?r.timeSeconds:accuracy(r)}));const baseline=effectiveMetric==='hf'?stats.hf.base:effectiveMetric==='time'?stats.time.base:stats.accuracy.base;
 const totals=filtered.reduce((v,r)=>({A:v.A+r.hitsA,C:v.C+r.hitsC,D:v.D+r.hitsD,miss:v.miss+r.misses,metal:v.metal+(r.metalHits||0),metalMiss:v.metalMiss+(r.metalMisses||0),penalties:v.penalties+r.procedurals+(r.noShootHits||0)}),{A:0,C:0,D:0,miss:0,metal:0,metalMiss:0,penalties:0});const total=totals.A+totals.C+totals.D+totals.miss;
 const change=(value:number|null,unit='%')=>value===null?'אין מספיק נתונים להשוואה':`${value>=0?'+':''}${value.toFixed(1)}${unit}`;
 const focus=getMyFocusItems().filter(f=>f.status!=='completed').sort((a,b)=>({high:0,medium:1,low:2}[a.priority]-{high:0,medium:1,low:2}[b.priority])).slice(0,3);
 return <div className={compact?'progress-panel':'progress-page'}>{!compact&&<div className="page-intro"><div className="eyebrow">YOUR PROGRESS</div><h1>ההתקדמות שלי</h1><p>השוואה באותה גרסת תרגיל, מחלקה ו-Power Factor.</p></div>}
 <section className="dashboard-card progress-card"><h2>התקדמות לאורך זמן</h2>
 {!groups.size?<div className="empty-state">עוד אין תוצאות עם תנאים מלאים להשוואה. תוצאות קודמות נשמרות בהיסטוריה.</div>:<>
 <label className="chart-selector">תרגיל ותנאים<select value={selected} onChange={e=>setChoice(e.target.value)}>{[...groups].map(([key,rows])=><option key={key} value={key}>{rows[0].exerciseTemplateName} · {rows[0].division} · {rows[0].powerFactor} · גרסה {rows[0].exerciseVersion?.slice(0,6)}</option>)}</select></label>
 {!compact&&<label className="chart-selector">תקופה<select value={period} onChange={e=>setPeriod(e.target.value)}><option value="all">כל התקופה</option><option value="30">30 ימים</option><option value="90">90 ימים</option><option value="365">שנה</option></select></label>}
 <p className="chart-caption">{filtered.length} תוצאות · אותם תנאים · חציון עד 5 המדידות האחרונות</p>
 <div className="metric-cards"><div className="metric-card"><span>דיוק — אחוז A</span><strong dir="ltr">{stats.accuracy.current===null?'—':stats.accuracy.current.toFixed(1)+'%'}</strong><small>{change(stats.accuracy.change,' נק׳ אחוז')}</small></div><div className="metric-card"><span>זמן · שניות</span><strong dir="ltr">{stats.time.current?.toFixed(2)||'—'}</strong><small>שיפור: {change(stats.time.change)}</small></div><div className="metric-card"><span>{mode==='points'?'נקודות':'Hit Factor'}</span><strong dir="ltr">{mode==='points'?(filtered.length?Math.max(...filtered.map(r=>r.rawPoints)):'—'):stats.hf.current?.toFixed(2)||'—'}</strong><small>{mode==='points'?'שיא בתקופה':change(stats.hf.change)}</small></div></div>
 <div className="stats-tabs">{(['hf','accuracy','time'] as const).filter(m=>mode!=='points'||m!=='hf').map(m=><button key={m} aria-pressed={effectiveMetric===m} onClick={()=>setMetric(m)}>{m==='hf'?'Hit Factor':m==='accuracy'?'דיוק':'זמן'}</button>)}</div>
 {chart.length?<div className="progress-chart" dir="ltr"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chart} margin={{top:12,right:18,left:-12,bottom:4}}><defs><linearGradient id={gradientId} x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#ae8654" stopOpacity={.25}/><stop offset="100%" stopColor="#ae8654" stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} stroke="#e9e4da"/><XAxis dataKey="date" minTickGap={35} tick={{fontSize:11}}/><YAxis domain={effectiveMetric==='accuracy'?[0,100]:[0,'auto']} tick={{fontSize:11}}/><Tooltip formatter={(v:number)=>[Number(v).toFixed(2),effectiveMetric==='hf'?'Hit Factor':effectiveMetric==='time'?'שניות':'אחוז A']}/>{baseline!==null&&<ReferenceLine y={baseline} stroke="#7d806f" strokeDasharray="5 5" label={{value:'רמת בסיס',position:'insideTopRight',fontSize:12}}/>}<Area dataKey="value" type="linear" connectNulls={false} stroke="#9b774a" strokeWidth={2.5} fill={`url(#${gradientId})`} dot={{r:4}} isAnimationActive={false}/></AreaChart></ResponsiveContainer></div>:<p className="empty-state">אין תוצאות בתקופה שנבחרה.</p>}
 <p className="chart-caption">{stats.observation}</p>{!compact&&<small>בסיס: 3 מדידות ראשונות. מגמה: 5 אחרונות, ללא חפיפה. נדרשות 8 מדידות. סף תצוגה: 3% בזמן ו-2 נקודות אחוז בדיוק — הגדרות המועדון.</small>}
 {filtered.length>0&&<p className="personal-best">שיא אישי בתקופה: <strong dir="ltr">{mode==='points'?Math.max(...filtered.map(r=>r.rawPoints)):Math.max(...filtered.map(r=>r.hitFactor)).toFixed(2)} {mode==='points'?'נק׳':'HF'}</strong></p>}
 </>}
 </section>
 {!compact&&<><section className="dashboard-card"><h2>פגיעות וענישה</h2><div className="distribution-bar">{[totals.A,totals.C,totals.D,totals.miss].map((n,i)=><span key={i} style={{width:total?`${n/total*100}%`:'0%'}}/>)}</div><div className="zone-grid">{(['A','C','D','miss'] as const).map(key=><div key={key}><span>{key==='miss'?'החטאות קרטון':key}</span><strong>{totals[key]}</strong><small>{total?(totals[key]/total*100).toFixed(1)+'%':'אין נתונים'}</small></div>)}</div><p>מתכת: {totals.metal} פגיעות · {totals.metalMiss} החטאות · ענישות: {totals.penalties}</p></section>
 <section className="dashboard-card"><h2>באימון הבא</h2>{!focus.length?<p>אין דגשים פתוחים.</p>:focus.map(f=><div className="result-history" key={f.id}><h3>{f.title}</h3><p>{f.description}</p><small>{f.instructorName} · {f.status==='in_progress'?'בעבודה':'פתוח'}</small>{f.status==='open'&&<button className="button-outline" onClick={()=>updateFocusItemStatus(f.id,'in_progress')}>התחלתי לעבוד על הדגש</button>}</div>)}<small>השלמת דגש מאושרת על ידי המדריך.</small></section>
 <section className="dashboard-card"><h2>היסטוריית תוצאות</h2><div className="result-history">{[...filtered,...results.filter(r=>!comparisonKey(r)&&(!cutoff||r.trainingDate>=cutoff))].sort((a,b)=>b.trainingDate.localeCompare(a.trainingDate)).map(r=><div key={r.id}><span><b>{r.trainingDate} · {r.exerciseTemplateName}</b><small>{r.timeSeconds} שנ׳ · A {r.hitsA} / C {r.hitsC} / D {r.hitsD} · החטאות {r.misses+(r.metalMisses||0)} · ענישות {r.procedurals+(r.noShootHits||0)}</small>{!comparisonKey(r)&&<small>תוצאה קודמת — תנאים חסרים, ללא השוואת מגמה</small>}</span><strong dir="ltr">{r.measurementType==='points'?r.rawPoints+' pts':r.hitFactor.toFixed(2)+' HF'}</strong></div>)}</div>{!results.length&&<p>התוצאות יופיעו לאחר האימון.</p>}</section></>}
 </div>;
};
