import React,{useRef,useEffect,useState} from 'react';
import {FalconLogo} from '../common/FalconLogo';
import {api,useApp} from '../../context/AppContext';
import {X,Eye,EyeOff} from 'lucide-react';
export const LoginModal:React.FC<{isOpen:boolean;onClose:()=>void}>=({isOpen,onClose})=>{
 const {loginPassword,activatePassword,showToast}=useApp();const dialog=useRef<HTMLDialogElement>(null);const [busy,setBusy]=useState(false),[setup,setSetup]=useState(false),[ownerRecovery,setOwnerRecovery]=useState(false),[login,setLogin]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[visible,setVisible]=useState(false);const activation=window.location.hash.startsWith('#activate=')?window.location.hash.slice(10):null;const creating=!!activation||setup;
 useEffect(()=>{if(isOpen){setPassword('');setConfirm('');api('/hosting/status').then(r=>{setSetup(r.setupAvailable===true);setOwnerRecovery(r.ownerRecovery===true);}).catch(()=>{});}},[isOpen]);
 useEffect(()=>{if(isOpen&&!dialog.current?.open)dialog.current?.showModal();else if(!isOpen&&dialog.current?.open)dialog.current.close();},[isOpen]);
 async function enter(e:React.FormEvent){e.preventDefault();if(creating&&password!==confirm){showToast('הסיסמאות אינן זהות','error');return;}setBusy(true);try{let activate=activation;if(!activate&&setup){const r=await api('/hosting/setup','POST',{});activate=r.activationUrl.split('#activate=')[1];}if(await (activate?activatePassword(activate,password,login):loginPassword(login,password))){setPassword('');setConfirm('');setSetup(false);onClose();}}catch(e){showToast(e instanceof Error?e.message:'הכניסה נכשלה','error');}finally{setBusy(false);}}
 return <dialog ref={dialog} className="demo-dialog" onCancel={onClose} onClick={e=>{if(e.target===e.currentTarget)onClose();}}><div className="dialog-heading"><span className="eyebrow">{creating?'הגדרת סיסמה':'כניסה לחברים'}</span><button className="icon-button" aria-label="סגירה" onClick={onClose}><X size={20}/></button></div><div className="demo-brand"><FalconLogo size="lg"/></div><h2>{creating?'מגדירים כניסה אישית.':'ברוכים השבים.'}</h2><p>{setup?'הגדירו סיסמה לחשבון המנהל. מספר הטלפון שלכם ישמש לכניסה.':activation?'בחרו סיסמה לחשבון שהנהלת המועדון יצרה עבורכם.':'היכנסו באמצעות מספר הטלפון והסיסמה שלכם.'}</p><form onSubmit={enter} className="space-y-4">{<label className="block">מספר טלפון<input className="activation-input" dir="ltr" type="tel" inputMode="tel" autoComplete="tel" required maxLength={30} value={login} onChange={e=>setLogin(e.target.value)}/></label>}<label className="block">סיסמה<div className="flex gap-2"><input className="activation-input flex-1" dir="ltr" type={visible?'text':'password'} autoComplete={creating?'new-password':'current-password'} required minLength={creating?6:1} maxLength={72} value={password} onChange={e=>setPassword(e.target.value)}/><button type="button" aria-label={visible?'הסתרת סיסמה':'הצגת סיסמה'} className="icon-button" onClick={()=>setVisible(!visible)}>{visible?<EyeOff/>:<Eye/>}</button></div></label>{creating&&<><small className="block">לפחות 6 תווים, כולל אותיות וספרות. מומלץ לבחור סיסמה ארוכה יותר.</small><label className="block">אימות סיסמה<input className="activation-input" dir="ltr" type={visible?'text':'password'} autoComplete="new-password" required value={confirm} onChange={e=>setConfirm(e.target.value)}/></label></>}<button className="button-primary w-full" disabled={busy}>{busy?'מאמת…':creating?'הגדרת סיסמה וכניסה':'כניסה'}</button></form><>{ownerRecovery&&!creating&&<button type="button" className="text-link mt-4" disabled={busy} onClick={async()=>{try{const r=await api('/hosting/recover','POST',{});location.hash=r.activationUrl.split('#')[1];setSetup(true);setPassword('');setConfirm('');}catch(e){showToast(e instanceof Error?e.message:'השחזור נכשל','error');}}}>שחזור סיסמת מנהל באמצעות חשבון ChatGPT</button>}</><p className="demo-note">שכחתם סיסמה? פנו למנהל המועדון לקבלת קישור שחזור לאחר אימות זהות.</p></dialog>;
};
