import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {readFileSync,readdirSync} from 'node:fs';
import {storage,loadContext,commitContext,seed,saveUser,users,put,get,db,tx,invitation} from './db.mjs';
const sqlite=new DatabaseSync(':memory:');for(const file of readdirSync('drizzle').filter(n=>n.endsWith('.sql')))sqlite.exec(readFileSync('drizzle/'+file,'utf8'));
function prepare(sql){return {sql,args:[],bind(...args){return {...this,args};},async first(){return sqlite.prepare(sql).get(...this.args);}};}
const binding={prepare,async batch(statements){sqlite.exec('BEGIN');try{const result=statements.map(s=>{const q=sqlite.prepare(s.sql);if(/^SELECT/.test(s.sql))return {results:q.all(...s.args.map(v=>v instanceof ArrayBuffer?new Uint8Array(v):v)),meta:{changes:0}};const r=q.run(...s.args.map(v=>v instanceof ArrayBuffer?new Uint8Array(v):v));return {results:[],meta:{changes:Number(r.changes)}};});sqlite.exec('COMMIT');return result;}catch(e){sqlite.exec('ROLLBACK');throw e;}}};
const origin='https://test.example.com';
test('D1 persists defaults and accounts with optimistic revision guard',async()=>{const s=await loadContext(binding,origin);await storage.run(s,()=>{seed();saveUser({id:'admin',email:'admin@example.com',roles:['admin']});});assert.equal(await commitContext(binding,s),true);const fresh=await loadContext(binding,origin);storage.run(fresh,()=>{assert.equal(users()[0].id,'admin');assert.equal(get('pages','public').heroTitle,'נץ המדבר');});});
test('Concurrent revision prevents partial writes and duplicate capacity decisions',async()=>{const a=await loadContext(binding,origin),b=await loadContext(binding,origin);storage.run(a,()=>put('registrations',{id:'one',status:'confirmed'}));storage.run(b,()=>put('registrations',{id:'two',status:'confirmed'}));assert.equal(await commitContext(binding,a),true);assert.equal(await commitContext(binding,b),false);assert.equal(sqlite.prepare("SELECT COUNT(*) AS n FROM records WHERE kind='registrations'").get().n,1);});
test('Public key BLOB, sessions and one-use challenge updates survive D1',async()=>{const s=await loadContext(binding,origin);storage.run(s,()=>{db.prepare('INSERT INTO passkeys VALUES(?,?,?,?,?)').run('key','admin',new Uint8Array([1,2,3]),0,'[]');db.prepare('INSERT INTO sessions VALUES(?,?,?,?,?)').run('session','admin',1,2,3);db.prepare('UPDATE sessions SET touched=? WHERE hash=?').run(5,'session');db.prepare('INSERT INTO challenges VALUES(?,?,?,?,?,?)').run('challenge','nonce','login',null,null,100);db.prepare('DELETE FROM challenges WHERE hash=?').run('challenge');});assert.equal(await commitContext(binding,s),true);const fresh=await loadContext(binding,origin);storage.run(fresh,()=>{assert.deepEqual([...db.prepare('SELECT * FROM passkeys WHERE id=?').get('key').public_key],[1,2,3]);assert.equal(db.prepare('SELECT * FROM sessions WHERE hash=?').get('session').touched,5);assert.equal(db.prepare('SELECT * FROM challenges WHERE hash=?').get('challenge'),undefined);});});
test('Rollback does not commit failed operation; invitation matches hosted origin',async()=>{const s=await loadContext(binding,origin);storage.run(s,()=>{assert.throws(()=>tx(()=>{put('news',{id:'bad'});throw Error('stop');}));assert.equal(get('news','bad'),null);const url=invitation(users()[0]);assert.ok(url.startsWith(origin+'/#activate='));});assert.equal(await commitContext(binding,s),true);assert.equal(sqlite.prepare("SELECT COUNT(*) AS n FROM records WHERE id='bad'").get().n,0);});
