import {z} from 'zod';
const text=(max=500)=>z.string().max(max);const id=text(100).min(1);const date=text(30);const clock=z.string().regex(/^\d{2}:\d{2}$/).refine(v=>v.slice(0,2)<24&&v.slice(3)<60);const count=z.number().int().min(0).max(10000);const roles=z.array(z.enum(['shooter','instructor','admin'])).min(1).max(3);
const baseUserSchema=z.object({id:id.optional(),fullName:text(100).min(1),email:z.union([z.literal(''),z.string().email().max(200)]).default(''),phone:text(30).min(1),role:z.enum(['shooter','instructor','admin']).default('shooter'),roles:roles.default(['shooter']),membershipStatus:z.enum(['active','suspended','expired','pending']).default('active'),ipscCourseVerified:z.boolean().default(false),ipscCourseDetails:text(1000).optional(),joinedDate:date.default(()=>new Date().toISOString().slice(0,10)),twoFactorEnabled:z.boolean().optional(),mustChangePassword:z.boolean().optional(),temporaryPassword:z.string().min(6).max(72).optional()});
export const trainingSchema=z.object({id,title:text(150).min(1),type:text(150),description:text(4000),date:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),startTime:clock,endTime:clock,location:text(300),locationMapUrl:z.union([z.literal(''),z.url().regex(/^https:\/\//)]).optional(),instructorIds:z.array(id).max(20),instructorNames:z.array(text(100)).max(20),maxCapacity:z.number().int().min(1).max(200),registeredCount:count,waitlistCount:count,eligibilityRequirements:text(2000),registrationOpenDate:date,registrationCloseDate:date,cancelCutoffHours:z.number().min(0).max(168),status:z.enum(['scheduled','in_progress','completed','cancelled']),priceNote:text(300)});
export const resultSchema=z.object({trainingId:id,userId:id,exerciseTemplateId:id,hitsA:count,hitsC:count,hitsD:count,misses:count,procedurals:count,timeSeconds:z.number().positive().max(36000),division:z.enum(['Open','Standard','Classic','Production','Production Optics','Optics','Revolver']).optional(),metalHits:count.default(0),metalMisses:count.default(0),noShootHits:count.default(0),powerFactor:z.enum(['minor','major']).default('minor'),notes:text(2000).optional()});
export const focusSchema=z.object({id,userId:id,title:text(200).min(1),description:text(2000),priority:z.enum(['high','medium','low']),status:z.enum(['open','in_progress','completed']),createdTrainingId:id,createdDate:date,updatedDate:date.optional(),completedDate:date.optional(),instructorName:text(100)});
export const feedbackSchema=z.object({id,trainingId:id,userId:id,status:z.enum(['draft','published']),summary:text(4000).min(1),strengths:z.array(text(1000)).max(30),improvements:z.array(text(1000)).max(30),focusItems:z.array(focusSchema).max(30),internalInstructorNote:text(4000).optional()});
export const leadSchema=z.object({type:z.enum(['course_inquiry','club_join']),licenseStatus:z.enum(['licensed','approval_needed','discuss']).optional(),fullName:text(100).min(2),phone:text(30).min(7),email:z.union([z.literal(''),z.email().max(200)]),availability:text(500).optional(),previousExperience:text(2000).optional(),courseDetails:text(2000).optional(),courseDate:date.optional(),notes:text(4000).optional()});
export const newsSchema=z.object({id,category:z.enum(['club','israel','world']),title:text(200).min(1),excerpt:text(1000),content:text(20000),imageUrl:z.union([z.literal(''),z.string().startsWith('/assets/').max(300),z.url().regex(/^https:\/\//).max(2000)]),publishDate:date,status:z.enum(['draft','published','archived']),author:text(100),sourceUrl:z.union([z.literal(''),z.url().regex(/^https:\/\//).max(2000)]).optional()});
const socialUrl=hosts=>z.string().trim().max(2000).refine(value=>{
 if(!value)return true;
 try{const url=new URL(value);return url.protocol==='https:'&&!url.username&&!url.password&&!url.port&&hosts.includes(url.hostname);}catch{return false;}
},'קישור HTTPS לרשת החברתית הנבחרת נדרש').optional().default('');
export const pagesSchema=z.object({id:z.literal('public'),heroTitle:text(150).min(1),heroAccent:text(150).min(1),heroBody:text(2000),aboutTitle:text(200).min(1),aboutBody:text(4000),sportTitle:text(200).min(1),sportBody:text(4000),whatsappUrl:socialUrl(['wa.me','api.whatsapp.com','chat.whatsapp.com']),instagramUrl:socialUrl(['instagram.com','www.instagram.com']),facebookUrl:socialUrl(['facebook.com','www.facebook.com','m.facebook.com','fb.com','www.fb.com'])});
export const leadUpdate=z.object({status:z.enum(['new','in_progress','pending_docs','approved','rejected','closed']),internalNotes:text(4000).optional(),assignedTo:id.optional()});

const birthDate=z.union([z.literal(''),z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v=>{const d=new Date(v);return Number.isFinite(d.getTime())&&d.toISOString().slice(0,10)===v&&v>='1900-01-01'&&d<=new Date();})]);
const validDate=z.union([z.literal(''),z.string().regex(/^\d{4}-\d{2}-\d{2}$/)]);
export const profileSchema=z.object({birthDate:birthDate.optional(),shooterNumber:text(40).regex(/^[A-Za-z0-9-]*$/).optional(),division:z.enum(['','Open','Standard','Classic','Production','Production Optics','Optics','Revolver']).optional(),classification:z.enum(['','U','D','C','B','A','M','GM']).optional(),firearmLicenseExpiry:validDate.optional(),healthDeclarationExpiry:validDate.optional(),insuranceExpiry:validDate.optional()});

export const userSchema=baseUserSchema.extend({...profileSchema.shape,username:z.string().min(3).max(60).regex(/^[A-Za-z0-9._@+-]+$/).optional()});

