import {env} from 'cloudflare:workers';
import express from 'express';
import helmet from 'helmet';
// Request limits are enforced persistently in the Worker before this API.
const rateLimit=()=>((req,res,next)=>next());
import cookieParser from 'cookie-parser';
import {z} from 'zod';

import bcrypt from 'bcryptjs';
import {normalizePhone} from './phone.mjs';
import {definitionSchema,makeDefinition,scoreResult} from './exercises.mjs';
import {db,all,get,put,remove,user,users,saveUser,uuid,token,hash,tx,invitation,audit} from './db.mjs';
import * as schemas from './schemas.mjs';

const origin=env.APP_ORIGIN;
const rpID=new URL(origin).hostname;
const production=true;
if(production&&!origin.startsWith('https://'))throw Error('Production requires an HTTPS APP_ORIGIN.');
const cookieName=production?'__Host-df_session':'df_session';
const cookieOptions={httpOnly:true,secure:production,sameSite:'strict',path:'/'};
export const app=express();app.disable('x-powered-by');
app.use(helmet({contentSecurityPolicy:{directives:{defaultSrc:["'self'"],scriptSrc:["'self'"],styleSrc:["'self'","'unsafe-inline'",'https://fonts.googleapis.com'],fontSrc:["'self'",'https://fonts.gstatic.com'],imgSrc:["'self'",'data:','https:'],connectSrc:["'self'"],frameAncestors:["'none'"],formAction:["'self'"],upgradeInsecureRequests:production?[]:null}},strictTransportSecurity:production?undefined:false}));
app.use('/api',rateLimit({windowMs:60000,limit:300,standardHeaders:'draft-8',legacyHeaders:false,message:{error:'יותר מדי בקשות. נסו שוב בעוד רגע.'}}));
app.use(express.json({limit:'10mb'}));app.use(cookieParser());
app.use('/api',(req,res,next)=>{res.set('Cache-Control','no-store');if(!['GET','HEAD','OPTIONS','DELETE'].includes(req.method)){const reqOrigin=req.get('Origin');if(reqOrigin&&reqOrigin!==origin&&!reqOrigin.includes('localhost')&&!reqOrigin.includes('127.0.0.1'))return res.status(403).json({error:'בקשה ממקור לא מורשה'});const hasBody=Number(req.get('content-length')||0)>0||Boolean(req.get('transfer-encoding'));if(hasBody&&req.get('content-type')&&!req.is('application/json'))return res.status(415).json({error:'נדרש JSON'});}next();});
const error=(code,message)=>{const e=new Error(message);e.status=code;throw e;};
const read=(schema,obj)=>{const p=schema.safeParse(obj);if(!p.success)error(400,'נתונים לא תקינים. בדקו את השדות.');return p.data;};
const authLimiter=rateLimit({windowMs:15*60000,limit:process.env.NODE_ENV==='test'?500:60,standardHeaders:'draft-8',legacyHeaders:false,message:{error:'יותר מדי ניסיונות כניסה. נסו שוב מאוחר יותר.'}});
app.use('/api/auth',authLimiter);
app.use((req,res,next)=>{const value=req.cookies[cookieName];if(value){const s=db.prepare('SELECT * FROM sessions WHERE hash=?').get(hash(value));if(s&&s.expires>Date.now()&&s.touched>Date.now()-30*60000){req.user=user(s.user_id);req.session=s;db.prepare('UPDATE sessions SET touched=? WHERE hash=?').run(Date.now(),s.hash);}else{db.prepare('DELETE FROM sessions WHERE hash=?').run(hash(value));res.clearCookie(cookieName,cookieOptions);}}next();});
const auth=req=>{if(!req.user)error(401,'יש להתחבר לחשבון');return req.user;};
const active=req=>{const u=auth(req);if(u.membershipStatus!=='active')error(403,'החברות במועדון אינה פעילה');return u;};
const admin=(req)=>{const u=active(req);if(!u.roles.includes('admin'))error(403,'אין הרשאה לפעולה זו');return u;};
const assigned=(req,t)=>{const u=active(req);if(!t)error(404,'אימון לא נמצא');if(!u.roles.includes('admin')&&!(u.roles.includes('instructor')&&t.instructorIds.includes(u.id)))error(403,'אין הרשאה לאימון זה');return u;};
const roster=(t,id)=>all('registrations').some(r=>r.trainingId===t.id&&r.userId===id&&r.status==='confirmed');
const issueSession=(res,u)=>{const value=token(),now=Date.now();db.prepare('INSERT INTO sessions VALUES(?,?,?,?,?)').run(hash(value),u.id,now,now,now+8*3600000);res.cookie(cookieName,value,{...cookieOptions,maxAge:8*3600000});};

const inviteRow=value=>{const row=db.prepare('SELECT * FROM invitations WHERE hash=?').get(hash(value));if(!row||row.expires<Date.now())error(400,'קישור ההפעלה אינו תקין או שפג תוקפו');return row;};
const isSuper=u=>!!u&&get('platform','owner')?.userId===u.id;
const publicUser=u=>u?{...u,isSuperAdmin:isSuper(u)}:null;
const uniquePhone=(phone,id)=>{const value=normalizePhone(phone);if(!value)error(400,'מספר טלפון לא תקין');if(users().some(x=>x.id!==id&&normalizePhone(x.phone)===value))error(409,'מספר הטלפון כבר משויך לחשבון');return value;};
const passwordSchema=z.string().min(6).max(72).refine(v=>/\p{L}/u.test(v)&&/\d/.test(v),'נדרשות אותיות וספרות').refine(v=>Buffer.byteLength(v,'utf8')<=72&&!v.includes('\0'),'הסיסמה ארוכה מדי').refine(v=>!['password1234','123456789012','qwerty123456','111111111111','Password123!'].includes(v),'בחרו סיסמה אחרת');
app.post('/api/auth/password/activate',async(req,res)=>{const {activation,password,phone}=read(z.object({phone:z.string().max(30).optional(),activation:z.string().min(30).max(200),password:passwordSchema}),req.body);const inv=inviteRow(activation),u=user(inv.user_id);if(!u)error(400,'קישור לא תקין');if(u.phone&&phone&&normalizePhone(u.phone)!==normalizePhone(phone))error(400,'מספר הטלפון אינו תואם לחשבון');if(isSuper(u)&&inv.recovery!==2)error(403,'שחזור מנהל על רק באמצעות בעל החשבון');const phoneValue=uniquePhone(u.phone||phone,u.id);const passwordHash=await bcrypt.hash(password,12);tx(()=>{const current=inviteRow(activation);put('credentials',{id:u.id,passwordHash,version:uuid(),failed:0,lockedUntil:0});db.prepare('DELETE FROM sessions WHERE user_id=?').run(u.id);db.prepare('DELETE FROM passkeys WHERE user_id=?').run(u.id);db.prepare('DELETE FROM invitations WHERE hash=?').run(current.hash);saveUser({...u,phone:phoneValue,twoFactorEnabled:false});audit(u,'password-activated',u.id);});issueSession(res,user(u.id));res.json({success:true});});
app.post('/api/auth/password/login',async(req,res)=>{const {login,password}=read(z.object({login:z.string().min(1).max(200),password:z.string().min(1).max(200)}),req.body);const value=normalizePhone(login);const matches=value?users().filter(x=>normalizePhone(x.phone)===value):[];const u=matches.length===1?matches[0]:null,c=u?get('credentials',u.id):null;const dummy='$2b$12$R9h/cIPz0gi.URNNX3kh2OPST9/PgBkqquzi.Ss7KIUgO2t0jWMUW';const valid=await bcrypt.compare(password,c?.passwordHash||dummy);if(!u||!c||c.lockedUntil>Date.now()||!valid){if(c&&c.lockedUntil<=Date.now()){const failed=(c.lockedUntil>0?0:(c.failed||0))+1;put('credentials',{...c,failed,lockedUntil:failed>=5?Date.now()+15*60000:0});}error(401,'פרטי הכניסה שגויים או שהכניסה חסומה זמנית. נסו שוב מאוחר יותר.');}put('credentials',{...c,failed:0,lockedUntil:0});issueSession(res,u);audit(u,'password-login',u.id);res.json({success:true,mustChangePassword:!!(u.mustChangePassword||c.mustChangePassword)});});
app.post('/api/auth/password/change',async(req,res)=>{const u=auth(req);const {currentPassword,password}=read(z.object({currentPassword:z.string().max(200),password:passwordSchema}),req.body);const c=get('credentials',u.id);if(!c||!await bcrypt.compare(currentPassword,c.passwordHash))error(401,'הסיסמה הנוכחית אינה נכונה');const passwordHash=await bcrypt.hash(password,12);put('credentials',{id:u.id,passwordHash,version:uuid(),failed:0,lockedUntil:0,mustChangePassword:false});saveUser({...u,mustChangePassword:false});db.prepare('DELETE FROM sessions WHERE user_id=?').run(u.id);issueSession(res,user(u.id));audit(u,'password-changed',u.id);res.json({success:true});});
app.use('/api/auth/enroll',(req,res)=>res.status(410).json({error:'השתמשו בשם משתמש וסיסמה'}));app.use('/api/auth/login',(req,res)=>res.status(410).json({error:'השתמשו בשם משתמש וסיסמה'}));
app.post('/api/auth/logout',(req,res)=>{if(req.session)db.prepare('DELETE FROM sessions WHERE hash=?').run(req.session.hash);res.clearCookie(cookieName,cookieOptions);res.json({success:true});});
function state(req){const u=req.user;const pages=get('pages','public');const empty={currentUser:publicUser(u),users:u?[publicUser(u)]:[],trainings:[],registrations:[],exerciseTemplates:[],exerciseResults:[],focusItems:[],feedbacks:[],leads:[],news:all('news').filter(n=>n.status==='published'),pages};if(!u||u.membershipStatus!=='active')return empty;const role=req.query.role||u.role;if(!u.roles.includes(role))error(403,'אין הרשאה לתפקיד זה');const privileged=role==='admin';const instructor=role==='instructor';const trainings=all('trainings').filter(t=>privileged||!instructor||t.instructorIds.includes(u.id));const trainingIds=new Set(trainings.map(t=>t.id));const registrations=all('registrations').filter(r=>privileged||(instructor?trainingIds.has(r.trainingId):r.userId===u.id));const ownerIds=new Set(registrations.map(r=>r.userId));const feedbacks=all('feedbacks').filter(f=>privileged||(instructor?trainingIds.has(f.trainingId):f.userId===u.id&&f.status==='published')).map(f=>{if(privileged||instructor)return f;const {internalInstructorNote,...publicFeedback}=f;return publicFeedback;});const publishedFocus=new Set(feedbacks.filter(f=>f.status==='published').flatMap(f=>f.focusItems.map(i=>i.id)));return {...empty,users:(privileged?users():instructor?users().filter(x=>ownerIds.has(x.id)||x.id===u.id):[u]).map(publicUser),trainings,registrations,exerciseTemplates:all('templates').filter(x=>!x.trainingId||trainingIds.has(x.trainingId)),exerciseResults:all('results').filter(r=>privileged||(instructor?trainingIds.has(r.trainingId):r.userId===u.id)),feedbacks,focusItems:all('focus').filter(f=>privileged||(instructor?ownerIds.has(f.userId):f.userId===u.id&&publishedFocus.has(f.id))),leads:privileged?all('leads'):[],news:privileged?all('news'):empty.news};}
app.get('/api/state',(req,res)=>res.json(state(req)));
app.post('/api/leads',rateLimit({windowMs:3600000,limit:10,standardHeaders:'draft-8',legacyHeaders:false}),(req,res)=>{const lead=read(schemas.leadSchema,req.body);const saved={...lead,id:uuid(),status:'new',createdAt:new Date().toISOString()};put('leads',saved);res.status(201).json({success:true});});
app.patch('/api/leads/:id',(req,res)=>{const u=admin(req);const l=get('leads',req.params.id);if(!l)error(404,'פנייה לא נמצאה');put('leads',{...l,...read(schemas.leadUpdate,req.body)});audit(u,'lead-updated',l.id);res.json({success:true});});
app.post('/api/leads/:id/convert',(req,res)=>{const a=admin(req);const l=get('leads',req.params.id);if(!l)error(404,'פנייה לא נמצאה');if(l.userId)error(409,'כבר נוצר חשבון לפנייה זו');const u={id:uuid(),fullName:l.fullName,email:(l.email||'').toLowerCase(),phone:uniquePhone(l.phone,null),role:'shooter',roles:['shooter'],membershipStatus:'pending',ipscCourseVerified:false,ipscCourseDetails:l.courseDetails||'',joinedDate:new Date().toISOString().slice(0,10),twoFactorEnabled:false};if(u.email&&users().some(x=>x.email&&x.email.toLowerCase()===u.email))error(409,'כתובת הדוא״ל כבר קיימת');tx(()=>{saveUser(u);put('leads',{...l,status:'pending_docs',userId:u.id});audit(a,'lead-converted',u.id);});res.json({user:u,activationUrl:invitation(u)});});
app.put('/api/users/:id',async(req,res)=>{const a=admin(req);const rawBody={...req.body,id:req.params.id||req.body.id||uuid()};const u=read(schemas.userSchema,rawBody);if(!u.roles.includes(u.role))error(400,'התפקיד הראשי חייב להיכלל בהרשאות');const old=user(u.id);if(isSuper(old)&&(a.id!==old.id||JSON.stringify(u.roles)!==JSON.stringify(old.roles)||u.role!==old.role||u.membershipStatus!==old.membershipStatus))error(403,'חשבון מנהל העל מוגן');u.phone=uniquePhone(u.phone,u.id);if(u.username&&users().some(x=>x.id!==u.id&&((x.username||'').toLowerCase()===u.username.toLowerCase()||(x.email&&x.email.toLowerCase()===u.username.toLowerCase()))))error(409,'שם המשתמש כבר קיים');if(u.email&&users().some(x=>x.id!==u.id&&x.email&&x.email.toLowerCase()===u.email.toLowerCase()))error(409,'כתובת הדוא״ל כבר קיימת');if(old?.roles.includes('admin')&&old.membershipStatus==='active'&&(!u.roles.includes('admin')||u.membershipStatus!=='active')&&!users().some(x=>x.id!==u.id&&x.roles.includes('admin')&&x.membershipStatus==='active'))error(400,'לא ניתן להסיר את המנהל הפעיל האחרון');let setTempPassword=false;if(rawBody.temporaryPassword){const tempPass=read(passwordSchema,rawBody.temporaryPassword);const passwordHash=await bcrypt.hash(tempPass,12);put('credentials',{id:u.id,passwordHash,version:uuid(),failed:0,lockedUntil:0,mustChangePassword:true});u.mustChangePassword=true;setTempPassword=true;}else if(!old&&!get('credentials',u.id)){u.mustChangePassword=false;}else if(old){u.mustChangePassword=old.mustChangePassword||false;}saveUser({...u,avatarVersion:old?.avatarVersion,email:(u.email||'').toLowerCase(),twoFactorEnabled:false});if(old&&(JSON.stringify(old.roles)!==JSON.stringify(u.roles)||old.membershipStatus!==old.membershipStatus))db.prepare('DELETE FROM sessions WHERE user_id=?').run(u.id);audit(a,'user-saved',u.id);res.json({success:true,...(!old&&!setTempPassword?{activationUrl:invitation(u)}:{})});});
app.delete('/api/users/:id',(req,res)=>{admin(req);if(isSuper(user(req.params.id)))error(403,'לא ניתן למחוק את מנהל העל');error(405,'מחיקת משתמשים אינה זמינה; ניתן להשעות חבר מועדון');});
app.post('/api/users/:id/invite',(req,res)=>{const a=admin(req);const u=user(req.params.id);if(!u)error(404,'משתמש לא נמצא');if(isSuper(u))error(403,'לא ניתן לאפס סיסמה של מנהל העל');const recovery=get('credentials',u.id)!=null||db.prepare('SELECT id FROM passkeys WHERE user_id=?').get(u.id)!=null;if(recovery&&req.body.confirmIdentity!==true)error(400,'יש לאמת זהות לפני איפוס סיסמה');audit(a,'activation-link-created',u.id);res.json({activationUrl:invitation(u,recovery)});});
app.put('/api/trainings/:id',(req,res)=>{const a=admin(req);const t=read(schemas.trainingSchema,{...req.body,id:req.params.id});const start=new Date(`${t.date}T${t.startTime}:00`);const end=new Date(`${t.date}T${t.endTime}:00`);if(!Number.isFinite(start.getTime())||end<=start||!Number.isFinite(new Date(t.registrationOpenDate).getTime())||!Number.isFinite(new Date(t.registrationCloseDate).getTime()))error(400,'בדקו תאריכים ושעות');if(new Date(t.registrationOpenDate)>new Date(t.registrationCloseDate))error(400,'פתיחת ההרשמה חייבת להיות לפני הסגירה');if(t.instructorIds.some(id=>!user(id)?.roles.includes('instructor')))error(400,'יש לבחור מדריכים מורשים');if(all('registrations').filter(r=>r.trainingId===t.id&&r.status==='confirmed').length>t.maxCapacity)error(400,'הקיבולת קטנה ממספר הרשומים');put('trainings',{...t,exerciseIds:get('trainings',t.id)?.exerciseIds||[],registeredCount:all('registrations').filter(r=>r.trainingId===t.id&&r.status==='confirmed').length,waitlistCount:all('registrations').filter(r=>r.trainingId===t.id&&r.status==='waitlist').length,instructorNames:t.instructorIds.map(id=>user(id).fullName)});audit(a,'training-saved',t.id);res.json({success:true});});
app.delete('/api/trainings/:id',(req,res)=>{const a=admin(req);const t=get('trainings',req.params.id);if(!t)error(404,'אימון לא נמצא');tx(()=>{put('trainings',{...t,status:'cancelled',registeredCount:0,waitlistCount:0});all('registrations').filter(r=>r.trainingId===t.id&&r.status!=='cancelled').forEach(r=>put('registrations',{...r,status:'cancelled'}));audit(a,'training-cancelled',t.id);});res.json({success:true});});
function recount(id){const t=get('trainings',id);const regs=all('registrations').filter(r=>r.trainingId===id);put('trainings',{...t,exerciseIds:get('trainings',t.id)?.exerciseIds||[],registeredCount:regs.filter(r=>r.status==='confirmed').length,waitlistCount:regs.filter(r=>r.status==='waitlist').length});}
app.post('/api/trainings/:id/register',(req,res)=>{const me=active(req);const target=req.body.userId||me.id;if(target!==me.id)admin(req);const u=user(target);if(!u||u.membershipStatus!=='active'||!u.roles.includes('shooter')||!u.ipscCourseVerified)error(403,'ההרשמה דורשת חברות פעילה ואימות קורס');const result=tx(()=>{const t=get('trainings',req.params.id);if(!t)error(404,'אימון לא נמצא');const now=Date.now();const start=new Date(`${t.date}T${t.startTime}:00`).getTime();const opens=new Date(t.registrationOpenDate).getTime();const closes=new Date(t.registrationCloseDate.length===10?t.registrationCloseDate+'T23:59:59':t.registrationCloseDate).getTime();if(t.status!=='scheduled'||now>=start||now<opens||now>closes)error(400,'ההרשמה לאימון אינה פתוחה');const regs=all('registrations').filter(r=>r.trainingId===t.id&&r.status!=='cancelled');if(regs.some(r=>r.userId===u.id))error(409,'כבר נרשמת לאימון זה');const wait=regs.filter(r=>r.status==='confirmed').length>=t.maxCapacity;put('registrations',{id:uuid(),trainingId:t.id,userId:u.id,userName:u.fullName,userPhone:u.phone,registeredAt:new Date().toISOString(),status:wait?'waitlist':'confirmed',...(wait?{waitlistPosition:regs.filter(r=>r.status==='waitlist').length+1}:{}),attendance:'not_marked',paymentOnSite:false});recount(t.id);audit(me,'registration-created',t.id);return {success:true,waitlist:wait,message:wait?'נוספת לרשימת המתנה':'נרשמת בהצלחה'};});res.json(result);});
app.post('/api/registrations/:id/cancel',(req,res)=>{const u=auth(req);tx(()=>{const r=get('registrations',req.params.id);if(!r)error(404,'הרשמה לא נמצאה');if(r.userId!==u.id)admin(req);if(r.status==='cancelled')error(409,'ההרשמה כבר בוטלה');const t=get('trainings',r.trainingId);if(!u.roles.includes('admin')&&new Date(`${t.date}T${t.startTime}:00`).getTime()-Date.now()<t.cancelCutoffHours*3600000)error(400,'מועד הביטול עבר. פנו למנהל המועדון');put('registrations',{...r,status:'cancelled',waitlistPosition:undefined});if(r.status==='confirmed'&&t.status==='scheduled'){const next=all('registrations').filter(x=>x.trainingId===t.id&&x.status==='waitlist'&&user(x.userId)?.membershipStatus==='active').sort((a,b)=>a.registeredAt.localeCompare(b.registeredAt))[0];if(next)put('registrations',{...next,status:'confirmed',waitlistPosition:undefined});}all('registrations').filter(x=>x.trainingId===t.id&&x.status==='waitlist').sort((a,b)=>a.registeredAt.localeCompare(b.registeredAt)).forEach((x,i)=>put('registrations',{...x,waitlistPosition:i+1}));recount(t.id);audit(u,'registration-cancelled',r.id);});res.json({success:true,message:'ההרשמה בוטלה'});});
app.patch('/api/registrations/:id/attendance',(req,res)=>{const r=get('registrations',req.params.id);if(!r)error(404,'הרשמה לא נמצאה');const u=assigned(req,get('trainings',r.trainingId));const b=read(z.object({attendance:z.enum(['not_marked','attended','absent']),paymentOnSite:z.boolean().optional()}),req.body);if(b.paymentOnSite!==undefined&&b.paymentOnSite!==r.paymentOnSite)admin(req);put('registrations',{...r,...b});audit(u,'attendance-updated',r.id);res.json({success:true});});
app.post('/api/trainings/:id/exercises',(req,res)=>{
 const t=get('trainings',req.params.id),u=assigned(req,t);
 const {exercises}=read(z.object({exercises:z.array(definitionSchema).min(1).max(30)}),req.body);
 tx(()=>{const ids=exercises.map(b=>{
  const source=b.sourceTemplateId?get('templates',b.sourceTemplateId):null;
  if(source?.trainingId&&source.trainingId!==t.id)error(403,'אין הרשאה לתבנית זו');
  const id=uuid(),tpl=makeDefinition(b,id,t.id),keys=['paper','hitsPerPaper','plates','poppers','noShoots','conditions','measurementType'];
  if(source?.version&&keys.every(k=>source[k]===tpl[k]))tpl.version=source.version;
  put('templates',tpl);
  if(b.saveToLibrary)put('templates',{...tpl,id:uuid(),trainingId:undefined,category:'מועדון'});
  return id;
 });put('trainings',{...t,exerciseIds:ids});audit(u,'training-exercises-saved',t.id);});res.json({success:true});
});
app.post('/api/results',(req,res)=>{
 const b=read(schemas.resultSchema,req.body),t=get('trainings',b.trainingId),u=assigned(req,t);
 if(!roster(t,b.userId))error(400,'היורה אינו רשום לאימון');
 const tpl=get('templates',b.exerciseTemplateId);
 if(!tpl?.version||!t.exerciseIds?.includes(tpl.id))error(400,'יש להגדיר תרגיל לאימון לפני הזנת תוצאה');
 let score;try{score=scoreResult(b,tpl);}catch(e){error(400,e.message);}
 const shooter=user(b.userId),division=b.division||shooter.division;if(!division)error(400,'יש לבחור מחלקת ירי');const saved={...b,id:uuid(),recordedAt:new Date().toISOString(),trainingDate:t.date,exerciseTemplateName:tpl.name,userName:shooter.fullName,...score,exerciseVersion:tpl.version,exerciseSnapshot:tpl,division,measurementType:tpl.measurementType};
 put('results',saved);audit(u,'result-created',saved.id);res.status(201).json({success:true});
});
app.put('/api/feedbacks/:id',(req,res)=>{const b=read(schemas.feedbackSchema,{...req.body,id:req.params.id});const t=get('trainings',b.trainingId);const u=assigned(req,t);if(!roster(t,b.userId))error(400,'היורה אינו רשום לאימון');const old=get('feedbacks',b.id);if(old&&(old.trainingId!==b.trainingId||old.userId!==b.userId))error(400,'לא ניתן לשנות בעלות משוב');const saved={...b,trainingDate:t.date,trainingTitle:t.title,instructorId:u.id,instructorName:u.fullName,createdAt:old?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString(),publishedAt:b.status==='published'?old?.publishedAt||new Date().toISOString():undefined};tx(()=>{saved.focusItems=b.focusItems.map(f=>{const existing=get('focus',f.id);if(existing&&existing.userId!==b.userId)error(400,'דגש אינו שייך ליורה');return {...f,userId:b.userId,createdTrainingId:t.id,instructorName:u.fullName};});put('feedbacks',saved);if(saved.status==='published')saved.focusItems.forEach(f=>put('focus',f));audit(u,'feedback-saved',b.id);});res.json({success:true});});
app.patch('/api/focus/:id',(req,res)=>{const u=auth(req);const f=get('focus',req.params.id);if(!f)error(404,'דגש לא נמצא');if(f.userId!==u.id)assigned(req,get('trainings',f.createdTrainingId));const {status}=read(z.object({status:z.enum(['open','in_progress','completed'])}),req.body);if(status==='completed')assigned(req,get('trainings',f.createdTrainingId));put('focus',{...f,status,updatedDate:new Date().toISOString().slice(0,10),completedDate:status==='completed'?new Date().toISOString().slice(0,10):undefined});audit(u,'focus-updated',f.id);res.json({success:true});});
app.put('/api/news/:id',(req,res)=>{const u=admin(req);const n=read(schemas.newsSchema,{...req.body,id:req.params.id});put('news',n);audit(u,'news-saved',n.id);res.json({success:true});});
app.delete('/api/news/:id',(req,res)=>{const u=admin(req);remove('news',req.params.id);audit(u,'news-deleted',req.params.id);res.json({success:true});});
app.put('/api/pages',(req,res)=>{const u=admin(req);put('pages',read(schemas.pagesSchema,req.body));audit(u,'pages-saved','public');res.json({success:true});});

app.patch('/api/profile', (req,res)=>{const u=auth(req),profile=read(schemas.profileSchema,req.body);saveUser({...u,...profile});audit(u,'profile-updated',u.id);res.json({success:true});});
const photoAccess=(req,id)=>{const me=auth(req);if(me.id!==id&&!state(req).users.some(u=>u.id===id))error(403,'אין גישה לתמונה');};
app.get('/api/users/:id/photo',async(req,res)=>{photoAccess(req,req.params.id);const u=user(req.params.id);if(!u?.avatarVersion)error(404,'לא קיימת תמונה');const object=await env.BUCKET.get('avatars/'+u.id+'/'+u.avatarVersion);if(!object)error(404,'לא קיימת תמונה');res.set('Content-Type',object.httpMetadata?.contentType||'image/webp');res.set('X-Content-Type-Options','nosniff');res.set('Cache-Control','private, max-age=60');res.send(Buffer.from(await object.arrayBuffer()));});
app.post('/api/users/:id/photo',async(req,res)=>{const me=auth(req);if(me.id!==req.params.id)admin(req);const u=user(req.params.id);if(isSuper(u)&&me.id!==u.id)error(403,'חשבון מנהל העל מוגן');if(!u)error(404,'משתמש לא נמצא');const b=read(z.object({image:z.string().min(10).max(90000),mime:z.enum(['image/webp','image/jpeg','image/png'])}),req.body);const bytes=Buffer.from(b.image,'base64');if(bytes.length>65000)error(413,'התמונה גדולה מדי');const valid=b.mime==='image/webp'?bytes.subarray(0,4).toString()==='RIFF'&&bytes.subarray(8,12).toString()==='WEBP':b.mime==='image/png'?bytes.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])):bytes[0]===255&&bytes[1]===216&&bytes[2]===255;if(!valid)error(400,'קובץ תמונה לא תקין');const version=uuid();await env.BUCKET.put('avatars/'+u.id+'/'+version,bytes,{httpMetadata:{contentType:b.mime}});saveUser({...u,avatarVersion:version});audit(me,'photo-updated',u.id);res.json({success:true});});
app.delete('/api/users/:id/photo',async(req,res)=>{const me=auth(req);if(me.id!==req.params.id)admin(req);const u=user(req.params.id);if(isSuper(u)&&me.id!==u.id)error(403,'חשבון מנהל העל מוגן');if(!u)error(404,'משתמש לא נמצא');saveUser({...u,avatarVersion:undefined});res.json({success:true});});
app.get('/api/audit',(req,res)=>{admin(req);res.json(db.prepare('SELECT * FROM audit ORDER BY at DESC LIMIT 200').all());});

app.get('/api/hosting/status',(req,res)=>{const id=req.get('oai-authenticated-user-id');const email=req.get('oai-authenticated-user-email');if(env.PRIVATE_OWNER_SETUP!=='1'||!id||!email)return res.json({setupAvailable:false});const owner=get('platform','owner');if(owner&&owner.platformId!==id)return res.json({setupAvailable:false});const u=owner?user(owner.userId):null;res.json({ownerRecovery:!!u&&owner.platformId===id&&!!get('credentials',u.id),setupAvailable:!users().some(x=>x.roles.includes('admin'))||(u&&!get('credentials',u.id))});});
app.post('/api/hosting/recover',(req,res)=>{const id=req.get('oai-authenticated-user-id'),owner=get('platform','owner');if(env.PRIVATE_OWNER_SETUP!=='1'||!id||!owner||owner.platformId!==id)error(403,'אין הרשאה לשחזור מנהל');const u=user(owner.userId);if(!u)error(404,'החשבון לא נמצא');audit(u,'owner-recovery-requested',u.id);res.json({activationUrl:invitation(u,true,true)});});
app.post('/api/hosting/setup',(req,res)=>{const id=req.get('oai-authenticated-user-id');const email=req.get('oai-authenticated-user-email');if(env.PRIVATE_OWNER_SETUP!=='1'||!id||!email)error(403,'אין הרשאה להגדרת האתר');const owner=get('platform','owner');let u;if(owner){if(owner.platformId!==id)error(403,'אין הרשאה');u=user(owner.userId);if(!u||get('credentials',u.id))error(409,'החשבון כבר הוגדר');}else{if(users().some(x=>x.roles.includes('admin')))error(409,'כבר קיים מנהל');let name=req.get('oai-authenticated-user-full-name')||email;if(req.get('oai-authenticated-user-full-name-encoding')==='percent-encoded-utf-8'){try{name=decodeURIComponent(name);}catch{name=email;}}u={id:uuid(),email:email.toLowerCase(),fullName:name,phone:'',role:'admin',roles:['admin','instructor','shooter'],membershipStatus:'active',ipscCourseVerified:false,joinedDate:new Date().toISOString().slice(0,10),twoFactorEnabled:false};saveUser(u);put('platform',{id:'owner',platformId:id,userId:u.id});}res.json({activationUrl:invitation(u,true,true)});});
app.use('/api',(req,res)=>res.status(404).json({error:'נתיב לא נמצא'}));


app.use((err,req,res,next)=>{if(err.status)return res.status(err.status).json({error:err.message});console.error('Request failed:',err.stack);res.status(500).json({error:'אירעה שגיאה. נסו שוב.'});});
