import test from 'node:test';import assert from 'node:assert/strict';import {build} from 'esbuild';
import {normalizePhone} from './phone.mjs';import {scoreResult,definitionSchema} from './exercises.mjs';
const bundled=await build({entryPoints:['src/lib/statistics.ts'],bundle:true,write:false,format:'esm',platform:'node'});const {summarize,median,comparisonKey}=await import('data:text/javascript;base64,'+Buffer.from(bundled.outputFiles[0].text).toString('base64'));
test('Phone representations share one identity and malformed values fail',()=>{assert.equal(normalizePhone('050-123-4567'),'+972501234567');assert.equal(normalizePhone('+972 50 123 4567'),'+972501234567');assert.equal(normalizePhone('00972501234567'),'+972501234567');assert.equal(normalizePhone('abc0501234567'),null);assert.equal(normalizePhone('123'),null);});
test('Paper and metal scores respect PF and count constraints',()=>{const tpl={paper:2,hitsPerPaper:2,plates:1,poppers:1,noShoots:0,measurementType:'hit_factor'},r={hitsA:2,hitsC:1,hitsD:1,misses:0,metalHits:2,metalMisses:0,noShootHits:0,procedurals:0,timeSeconds:10,powerFactor:'minor'};assert.equal(scoreResult(r,tpl).rawPoints,24);assert.equal(scoreResult({...r,powerFactor:'major'},tpl).rawPoints,26);assert.throws(()=>scoreResult({...r,hitsA:3},tpl));assert.throws(()=>scoreResult({...r,metalHits:1},tpl));assert.equal(scoreResult({...r,procedurals:100},tpl).rawPoints,0);assert.equal(scoreResult(r,{...tpl,measurementType:'points'}).hitFactor,0);});
test('Unapproved examples cannot become training exercises',()=>{const draft={name:'Test',paper:1,hitsPerPaper:2,plates:0,poppers:0,noShoots:0,conditions:'Defined configuration',measurementType:'hit_factor',approvedForRange:false};assert.equal(definitionSchema.safeParse(draft).success,false);assert.equal(definitionSchema.safeParse({...draft,approvedForRange:true}).success,true);});
const rows=Array.from({length:8},(_,i)=>({id:String(i),recordedAt:`2026-01-0${i+1}`,trainingDate:`2026-01-0${i+1}`,exerciseVersion:'v1',division:'Standard',powerFactor:'minor',measurementType:'hit_factor',hitsA:i<3?6:8,hitsC:i<3?4:2,hitsD:0,misses:0,timeSeconds:i<3?20:18,hitFactor:i<3?2:3}));
test('Statistics use medians and require non-overlapping 3/5 samples',()=>{assert.equal(median([1,100,2]),2);const s=summarize([...rows].reverse());assert.equal(s.hf.change,50);assert.equal(s.time.change,10);assert.equal(s.accuracy.change,20);assert.equal(summarize(rows.slice(0,7)).hf.change,null);assert.equal(summarize(rows.map(r=>({...r,hitFactor:0}))).hf.change,null);});
test('Context groups distinguish PF and versions and exclude legacy rows',()=>{assert.notEqual(comparisonKey(rows[0]),comparisonKey({...rows[0],powerFactor:'major'}));assert.notEqual(comparisonKey(rows[0]),comparisonKey({...rows[0],exerciseVersion:'v2'}));assert.notEqual(comparisonKey(rows[0]),comparisonKey({...rows[0],division:'Production'}));assert.equal(comparisonKey({...rows[0],exerciseVersion:undefined}),null);});
