import React,{useEffect,useRef,useState} from 'react';
import {useApp} from '../../context/AppContext';
import {Registration,TrainingSession} from '../../types';
export const ScoreEntry:React.FC<{training:TrainingSession;shooter:Registration;onClose:()=>void;onNext:()=>void}>=({training,shooter,onClose,onNext})=>{
 const {exerciseTemplates,addExerciseResult,users}=useApp();const templates=exerciseTemplates.filter(t=>training.exerciseIds?.includes(t.id));
 const [selected,setSelected]=useState(templates[0]?.id||''),[busy,setBusy]=useState(false),[next,setNext]=useState(false),[pf,setPf]=useState<'minor'|'major'>('minor'),[error,setError]=useState(''),[division,setDivision]=useState(users.find(u=>u.id===shooter.userId)?.division||'');
 const [values,setValues]=useState({hitsA:0,hitsC:0,hitsD:0,misses:0,metalHits:0,metalMisses:0,noShootHits:0,procedurals:0,timeSeconds:0});const dialog=useRef<HTMLDialogElement>(null);
 useEffect(()=>{dialog.current?.showModal();},[]);useEffect(()=>{setValues({hitsA:0,hitsC:0,hitsD:0,misses:0,metalHits:0,metalMisses:0,noShootHits:0,procedurals:0,timeSeconds:0});setError('');setDivision(users.find(u=>u.id===shooter.userId)?.division||'');},[selected,shooter.userId]);
 const tpl=templates.find(t=>t.id===selected);const paper=(tpl?.paper||0)*(tpl?.hitsPerPaper||0),metal=(tpl?.plates||0)+(tpl?.poppers||0);
 const raw=Math.max(0,values.hitsA*5+values.hitsC*(pf==='major'?4:3)+values.hitsD*(pf==='major'?2:1)+values.metalHits*5-10*(values.misses+values.metalMisses+values.noShootHits+values.procedurals));
 return <dialog className="demo-dialog score-dialog" ref={dialog} onCancel={onClose}><div className="dialog-heading"><h2>תוצאה — {shooter.userName}</h2><button className="icon-button" onClick={onClose} aria-label="סגירה">×</button></div>
 {!tpl?<p>הגדירו תחילה את תרגילי האימון.</p>:<form className="space-y-4" onSubmit={async e=>{e.preventDefault();setError('');if(values.hitsA+values.hitsC+values.hitsD+values.misses!==paper||values.metalHits+values.metalMisses!==metal){setError('יש להשלים את מספר התוצאות לפי הרכב המטרות.');return;}setBusy(true);try{const saved=await addExerciseResult({trainingId:training.id,trainingDate:training.date,exerciseTemplateId:tpl.id,exerciseTemplateName:tpl.name,userId:shooter.userId,userName:shooter.userName,...values,division,powerFactor:pf,rawPoints:raw,hitFactor:values.timeSeconds>0?raw/values.timeSeconds:0});if(saved){if(next)onNext();else onClose();}}finally{setBusy(false);}}}>
 <label>תרגיל<select className="activation-input" value={selected} onChange={e=>setSelected(e.target.value)}>{templates.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><p>{paper} פגיעות בקרטון · {metal} מטרות מתכת</p>
<label>מחלקת ירי<select required className="activation-input" dir="ltr" value={division} onChange={e=>setDivision(e.target.value)}><option value="">בחרו מחלקה…</option>{['Open','Standard','Classic','Production','Production Optics','Optics','Revolver'].map(d=><option key={d}>{d}</option>)}</select></label>
 <label>Power Factor<select dir="ltr" className="activation-input" value={pf} onChange={e=>setPf(e.target.value as 'minor'|'major')}><option value="minor">Minor</option><option value="major">Major</option></select></label>
 <div className="exercise-counts">{([['hitsA','A'],['hitsC','C'],['hitsD','D'],['misses','החטאות קרטון'],['metalHits','מתכת — פגע'],['metalMisses','מתכת — החטאה'],['noShootHits','פגיעות במטרות ענישה'],['procedurals','ענישות פרוצדורליות']] as const).map(([key,label])=><label key={key}>{label}<div className="score-counter"><button type="button" aria-label={`הפחתה ${label}`} onClick={()=>setValues(v=>({...v,[key]:Math.max(0,v[key]-1)}))}>−</button><input type="number" min={0} max={10000} required value={values[key]} onChange={e=>setValues({...values,[key]:Number(e.target.value)})}/><button type="button" aria-label={`הוספה ${label}`} onClick={()=>setValues(v=>({...v,[key]:Math.min(10000,v[key]+1)}))}>+</button></div></label>)}</div>
 <label>זמן בשניות<input dir="ltr" type="number" inputMode="decimal" step="0.01" min="0.01" max={36000} required className="activation-input" value={values.timeSeconds||''} onChange={e=>setValues({...values,timeSeconds:Number(e.target.value)})}/></label>
 <div className="stat-strip"><div><strong>{raw}</strong><span>נקודות</span></div>{tpl.measurementType==='hit_factor'&&<div><strong>{values.timeSeconds>0?(raw/values.timeSeconds).toFixed(2):'—'}</strong><span>Hit Factor</span></div>}</div>
 {error&&<p role="alert">{error}</p>}<div className="flex flex-wrap gap-2"><button disabled={busy} className="button-primary" onClick={()=>setNext(false)}>שמירת תוצאה</button><button disabled={busy} className="button-outline" onClick={()=>setNext(true)}>שמירה והיורה הבא</button></div>
 </form>}</dialog>;
};
