import {env} from 'cloudflare:workers';
import {httpServerHandler} from 'cloudflare:node';
import {app} from '../server/index.mjs';
import {storage,loadContext,commitContext,seed,hash} from '../server/db.mjs';
app.listen(3000);
const http=httpServerHandler({port:3000});
const headers={'Cache-Control':'no-store','Content-Type':'application/json; charset=utf-8'};
function fail(status,error){return new Response(JSON.stringify({error}),{status,headers});}
async function limit(request,binding){const url=new URL(request.url),ip=request.headers.get('cf-connecting-ip')||request.headers.get('oai-authenticated-user-id')||'private';let period=60000,max=300,name='api';if(url.pathname.startsWith('/api/auth/')){period=15*60000;max=60;name='auth';}else if(url.pathname==='/api/leads'&&request.method==='POST'){period=3600000;max=10;name='leads';}const window=Math.floor(Date.now()/period)*period,key=hash(name+':'+ip);const r=await binding.prepare('INSERT INTO limits(key,count,window) VALUES(?,1,?) ON CONFLICT(key) DO UPDATE SET count=CASE WHEN limits.window=excluded.window THEN limits.count+1 ELSE 1 END,window=excluded.window RETURNING count').bind(key,window).first();return r.count<=max;}
export default {async fetch(request,bindings,ctx){try{const url=new URL(request.url);const configured=new URL(env.APP_ORIGIN);const originHeader=request.headers.get('origin');const hostHeader=request.headers.get('x-forwarded-host')||request.headers.get('host');const isOriginAllowed=url.origin===configured.origin||originHeader===configured.origin||hostHeader===configured.host||url.hostname==='localhost'||url.hostname==='127.0.0.1'||url.hostname.startsWith('192.168.')||url.hostname.startsWith('10.')||url.hostname.startsWith('172.');if(!isOriginAllowed)return fail(403,'כתובת האתר אינה מורשית');if(!url.pathname.startsWith('/api/')){const response=await bindings.ASSETS.fetch(request);return response;}if(!bindings.DB)return fail(503,'מסד הנתונים אינו זמין');if(!await limit(request,bindings.DB))return fail(429,'יותר מדי בקשות. נסו שוב מאוחר יותר.');const contentLength=Number(request.headers.get('content-length')||0);if(contentLength>5242880)return fail(413,'הבקשה גדולה מדי');const body=request.method==='GET'||request.method==='HEAD'||request.method==='DELETE'?undefined:await request.arrayBuffer();if(body&&body.byteLength>5242880)return fail(413,'הבקשה גדולה מדי');for(let attempt=0;attempt<4;attempt++){const s=await loadContext(bindings.DB,configured.origin);const response=await storage.run(s,async()=>{seed();const reqHeaders=new Headers(request.headers);if(!body||body.byteLength===0){reqHeaders.delete('content-type');reqHeaders.delete('content-length');}return http.fetch(new Request(request.url,{method:request.method,headers:reqHeaders,...(body&&body.byteLength>0?{body:body.slice(0)}:{})}),bindings,ctx);});const bytes=await response.arrayBuffer();if(await commitContext(bindings.DB,s))return new Response(bytes,{status:response.status,headers:response.headers});}return fail(409,'בוצע שינוי מקביל. נסו שוב.');}catch(error){console.error('Falcon request failed',error?.stack||String(error));return fail(503,'האתר אינו זמין כרגע. נסו שוב בעוד רגע.');}}};
