// Local, read-only presentation preview. Never loaded by the production Worker.
// No real account, password, session or database is used here.
import {createServer} from 'vite';
const pages={id:'public',heroTitle:'מועדון ירי מעשי',heroAccent:'נץ המדבר',heroBody:'ספורט, קהילה והדרכה אישית. יחד מתאמנים ומתקדמים.',aboutTitle:'על המועדון',aboutBody:'נץ המדבר הוא מועדון ירי מעשי המוקדש לספורט, לקהילה ולהתקדמות אישית. אנחנו מתאמנים באווירה מקצועית ותומכת.',sportTitle:'מה זה IPSC?',sportBody:'ספורט דינמי המשלב דיוק, עוצמה ומהירות.'};
const makeUser=(id,name,role)=>({id,fullName:name,email:`${id}@example.com`,phone:'0500000000',role,roles:['shooter','instructor','admin'],membershipStatus:'active',ipscCourseVerified:true,joinedDate:'2026-01-01',shooterNumber:'2048',division:'Production',classification:'B'});
const shooter=makeUser('preview-shooter','דניאל לדוגמה','shooter'), instructor=makeUser('preview-instructor','איתי לדוגמה','instructor'),admin=makeUser('preview-admin','מנהל לדוגמה','admin');
const date=new Date(Date.now()+7*86400000).toISOString().slice(0,10);
const training={id:'preview-training',title:'אימון לדוגמה',type:'אימון מועדון',description:'נתונים להמחשת העיצוב בלבד',date,startTime:'09:00',endTime:'11:00',location:'מתחם המועדון',instructorIds:[instructor.id],instructorNames:[instructor.fullName],maxCapacity:12,registeredCount:1,waitlistCount:0,eligibilityRequirements:'חברות פעילה ואישור המועדון',registrationOpenDate:'2026-01-01',registrationCloseDate:date,cancelCutoffHours:6,status:'scheduled',exerciseIds:['preview-exercise'],priceNote:'תשלום במקום בלבד'};
const template={id:'preview-exercise',name:'תרגיל לדוגמה',description:'תרגיל להמחשת העיצוב בלבד',category:'תרגיל מועדון',targetCount:4,maxPoints:40,measurementType:'hit_factor',version:'preview-v1',trainingId:training.id,paper:4,hitsPerPaper:2,plates:0,poppers:0,noShoots:0,approvedForRange:true,diagramUrl:'https://drive.google.com/file/d/1lZFV8SbioN5e5noxjy9Z4lenzP3leP7x/view'};
const resultDates=['2026-07-01','2026-07-15','2026-08-01','2026-08-15','2026-09-01','2026-09-10','2026-09-15','2026-09-20'];
const results=resultDates.map((trainingDate,i)=>({id:`preview-result-${i}`,trainingId:training.id,trainingDate,exerciseTemplateId:template.id,exerciseTemplateName:template.name,userId:shooter.id,userName:shooter.fullName,hitsA:6,hitsC:2,hitsD:0,misses:0,procedurals:0,timeSeconds:10-i*.5,rawPoints:36,hitFactor:36/(10-i*.5),exerciseVersion:template.version,exerciseSnapshot:template,division:shooter.division,powerFactor:'minor',measurementType:'hit_factor',recordedAt:trainingDate+'T12:00:00Z',metalHits:0,metalMisses:0,noShootHits:0}));
const focus={id:'preview-focus',userId:shooter.id,title:'עקביות בתוצאות',description:'דגש לדוגמה מהמשוב של המדריך',priority:'medium',status:'open',createdTrainingId:training.id,createdDate:'2026-09-15',instructorName:instructor.fullName};
const feedback={id:'preview-feedback',trainingId:training.id,trainingDate:'2026-09-15',trainingTitle:training.title,userId:shooter.id,instructorId:instructor.id,instructorName:instructor.fullName,status:'published',summary:'התקדמות טובה. באימון הבא נתמקד בדיוק ובעקביות.',strengths:['התמדה'],improvements:['עקביות'],focusItems:[focus],createdAt:'2026-09-15',publishedAt:'2026-09-15'};
function state(role){const user={shooter,instructor,admin}[role]||null;return {currentUser:user,pages,users:user?.role==='admin'?[shooter,instructor,admin]:[],trainings:user?[training]:[],registrations:user?[{id:'preview-registration',trainingId:training.id,userId:shooter.id,userName:shooter.fullName,userPhone:shooter.phone,registeredAt:'2026-09-15',status:'confirmed',attendance:'attended',paymentOnSite:false}]:[],exerciseTemplates:user?[template,{...template,id:'preview-library',trainingId:undefined,version:undefined,name:'CLC-01',sourceUrl:'https://www.ipsc.org/match-sanctioning/classifier-stages/',approvedForRange:false}]:[],exerciseResults:user?results:[],focusItems:user?[focus]:[],feedbacks:user?[feedback]:[],leads:user?.role==='admin'?[{id:'preview-lead',type:'course_inquiry',fullName:'מועמד לדוגמה',phone:'0500000000',email:'candidate@example.com',createdAt:'2026-09-20T12:00:00',status:'new'}]:[],news:[{id:'preview-news',category:'club',title:'קהילה שמתאמנת ומתקדמת',excerpt:'כתבה לדוגמה להמחשת העיצוב בלבד.',content:'תוכן לדוגמה — אינו עדכון אמיתי של המועדון.',imageUrl:'/assets/range-approved.webp',publishDate:'2026-09-15',status:'published',author:'הנהלת המועדון'}]};}
const reviewHtml=`<!doctype html><html lang="ru"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Desert Falcon — проверка дизайна</title><style>body{margin:0;background:#faf8f5;color:#19232c;font:15px system-ui}header{padding:12px 16px;border-bottom:1px solid #ddd;display:flex;flex-wrap:wrap;gap:12px;align-items:center}a{padding:8px 12px;background:#f0e7dc;color:#543c29;border-radius:8px}iframe{width:100%;height:calc(100dvh - 110px);border:0}small{display:block;padding:6px 16px}</style><header><strong>Desert Falcon · просмотр дизайна</strong><a href="/" target="site">Главная</a><a href="/?previewRole=shooter" target="site">Стрелок</a><a href="/?previewRole=instructor" target="site">Инструктор</a><a href="/?previewRole=admin" target="site">Админ</a></header><small>Только вымышленные данные. Сохранение и отправка отключены. Это локальный просмотр, без рабочей базы.</small><iframe name="site" title="Предпросмотр сайта" src="/"></iframe></html>`;
const port=Number(process.env.DESIGN_PREVIEW_PORT||5173);
const server=await createServer({server:{host:'127.0.0.1',port,strictPort:true},plugins:[{name:'local-design-fixtures',configureServer(server){server.middlewares.use((req,res,next)=>{const url=new URL(req.url,'http://127.0.0.1:5173');if(url.pathname==='/design-review.html'){res.setHeader('Content-Type','text/html; charset=utf-8');res.end(reviewHtml);return;}if(!url.pathname.startsWith('/api/'))return next();res.setHeader('Content-Type','application/json; charset=utf-8');if(req.method!=='GET'){res.statusCode=403;res.end(JSON.stringify({error:'תצוגת עיצוב בלבד — שמירה ושליחה אינן זמינות'}));return;}const referer=new URL(req.headers.referer||'http://127.0.0.1:5173/');const role=url.searchParams.get('role')||referer.searchParams.get('previewRole')||'guest';if(url.pathname==='/api/state')res.end(JSON.stringify(state(role)));else if(url.pathname==='/api/hosting/status')res.end(JSON.stringify({setupAvailable:false,ownerRecovery:false}));else res.end('{}');});}}]});
await server.listen();console.log(`\nOpen http://127.0.0.1:${port}/design-review.html\nRead-only local preview using fictional data. Stop with Ctrl+C.\n`);
